<table>
    <tr>
        <th><button type="button" class="action" data-trigger="trigger">Open Modal</button></th>
        <th><button type="button" class="action" data-trigger="trigger1">Open Magento Login Modal</button></th>
        <th><button>Open Custom Login Modal</button></th>
    </tr>
</table>
<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Magento Alert Model',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
    <div class="content">
        Magento Alert Model
    </div>
</div>

<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Magento Login Model',
            'trigger': '[data-trigger=trigger1]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
    <div class="materialContainer">


        <div class="box">

            <div class="title">LOGIN</div>

            <div class="input">
                <label for="name">Username</label>
                <input type="text" name="name" id="name">
                <span class="spin"></span>
            </div>

            <div class="input">
                <label for="pass">Password</label>
                <input type="password" name="pass" id="pass">
                <span class="spin"></span>
            </div>

            <div class="button login">
                <button><span>GO</span> <i class="fa fa-check"></i></button>
            </div>

            <a href="" class="pass-forgot">Forgot your password?</a>

        </div>

        <div class="overbox">
            <div class="material-button alt-2"><span class="shape"></span></div>

            <div class="title">REGISTER</div>

            <div class="input">
                <label for="regname">Username</label>
                <input type="text" name="regname" id="regname">
                <span class="spin"></span>
            </div>

            <div class="input">
                <label for="regpass">Password</label>
                <input type="password" name="regpass" id="regpass">
                <span class="spin"></span>
            </div>

            <div class="input">
                <label for="reregpass">Repeat Password</label>
                <input type="password" name="reregpass" id="reregpass">
                <span class="spin"></span>
            </div>

            <div class="button">
                <button><span>NEXT</span></button>
            </div>


        </div>

    </div>
</div>
<!--RequireJS-->
<!--<div data-mage-init='{"myjs": {}}'>-->
<!--    <a href="#" id="click-me">Click Me</a>-->
<!--</div>-->
<!---->
<!---->
<!--<div id="popup-modal" >-->
<!--    yes I am the modal.-->
<!--</div>-->
